### ISSUE TITLE
Add support for getting status

### ISSUE THREAD

**Issue by jmgilman** [c0sco/ansible-modules-bitwarden#21]
The way the module currently handles a locked vault is by throwing an error. There doesn't appear to be a way to check beforehand if vault data can be accessed - this makes conditional access difficult. My current workaround is a bit tedious:

```yaml
- block:
    - set_fact:
        status: "{{ lookup('bitwarden') }}"
        unlocked: true
  rescue:
    - set_fact:
        unlocked: false
- block:
    - set_fact:
        home: "{{ lookup('env','HOME') }}"
        key: "{{ lookup('bitwarden', item, field='item') }}"
    - name: SSH directory exists
      ansible.builtin.file:
        path: "{{ home }}/.ssh"
        state: directory
        mode: 0700
    - debug:
        msg: "{{ lookup('bitwarden', item,  itemid=key.id, attachments=true, output=home+'/.ssh/'+item ) }}"
    - debug:
        msg: "{{ lookup('bitwarden', item+'.pub',  itemid=key.id, attachments=true, output=home+'/.ssh/'+item+'.pub' ) }}"
  when: unlocked
```

Basically, I use blocks to catch the error thrown when the vault is locked and set `unlocked` accordingly to conditionally run steps that require the vault to be unlocked. It would be nice to have a dedicated lookup parameter to fetch vault status to avoid resorting to this hacky approach.
